FROM almalinux:latest

ENV container docker

RUN dnf -y install epel-release
RUN dnf config-manager --set-enabled crb
RUN dnf update -y
RUN dnf install perl-Time-Piece -y
RUN dnf install perl-Compress-Raw-Zlib -y
RUN dnf install perl-Compress-Zlib -y
RUN dnf install perl-HTTP-Cookies -y
RUN dnf install perl-libwww-perl -y
RUN dnf install perl-LWP-Protocol-https -y
RUN dnf install perl-Time-HiRes
RUN dnf install perl-File-Copy
RUN dnf install perl-JSON -y
RUN dnf install perl-JSON-PP -y
RUN dnf install perl-JSON-XS -y

RUN mkdir /var/zap2xml

RUN mkdir /mnt/export

RUN curl https://raw.githubusercontent.com/nateshull/zap2xml/master/zap2xml2.pl > /var/zap2xml/zap2xml2.pl

RUN curl https://raw.githubusercontent.com/nateshull/zap2xml/master/zap2xml.sh > /var/zap2xml/zap2xml.sh

RUN chmod -R 777 /mnt/export

RUN chmod -R 777 /var/zap2xml/*

ENV DEBUG="false"

ENV USER="BLANK"

ENV PASS="PASS"

ENV TIME="TIME"

ENTRYPOINT /var/zap2xml/zap2xml.sh
