FROM centos/perl-530-centos7

ENV container docker

RUN yum update -y
RUN yum install perl-Time-Piece -y

RUN mkdir /mnt/export

RUN mkdir /var/zap2xml

RUN curl https://raw.githubusercontent.com/nateshull/zap2xml/master/zap2xml2.pl > /var/zap2xml/zap2xml2.pl

RUN curl https://raw.githubusercontent.com/nateshull/zap2xml/master/zap2xml.sh > /var/zap2xml/zap2xml.sh

RUN chmod -R 777 /var/zap2xml/*

ENV DEBUG="false"

ENV USER="BLANK"

ENV PASS="PASS"

ENTRYPOINT /var/zap2xml/zap2xml.sh
